import type { Metadata } from "next";
import { Dancing_Script, Lexend } from "next/font/google";
import { Providers } from "@/components/providers";
import "@ec/ui/globals.css";
import type { PropsWithChildren } from "react";

// FONTS ***********************************************************************************************************************************
const base = Lexend({ variable: "--font-base", subsets: ["latin"] });
const heading = Dancing_Script({
	variable: "--font-heading",
	subsets: ["latin"],
});

// METADATA ********************************************************************************************************************************
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// ROOT ************************************************************************************************************************************
export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="fr" suppressHydrationWarning>
			{/* <head>
				<script src="https://unpkg.com/react-scan/dist/auto.global.js" />
			</head> */}
			<body className={`${base.variable} ${heading.variable} flex min-h-screen flex-col overflow-x-hidden antialiased`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
type RootLayoutProps = PropsWithChildren;
