import { ConvexClientProvider } from "@/lib/convex";
import { frFR } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Dancing_Script, Lexend } from "next/font/google";
import "./globals.css";

// FONTS ***********************************************************************************************************************************
const base = Lexend({ variable: "--font-base", subsets: ["latin"] });
const heading = Dancing_Script({ variable: "--font-heading", subsets: ["latin"] });

// METADATA ********************************************************************************************************************************
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ROOT ************************************************************************************************************************************
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fr">
      <body className={`${base.variable} ${heading.variable} flex min-h-screen flex-col overflow-x-hidden antialiased`}>
        <ClerkProvider localization={frFR}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}

// TYPES ***********************************************************************************************************************************
type RootLayoutProps = Readonly<{ children: React.ReactNode }>;
